### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by markypython** [vivek12345/react-polling-hook#2]
When I try to install this package I get the following error.  It doesn't look like this package exists on npm.

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/react-polling-hook - Not found
npm ERR! 404
npm ERR! 404  'react-polling-hook@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by vivek12345** [comment]
@markypython Sorry for the delay in reply. I have been occupied with some other work.

And yes you are right this has not been published yet on npm, because it lacks some testing and some unit test cases.

Once that is done, we can publish this.

If you are willing to raise a PR for the test cases, I would be happy to review and merge them.

**Comment by markypython** [comment]
I ended up just copying the code since it wasn't available on npm which works for now.  I too am very busy and don't have time to help out right now.

**Comment by jorisw** [comment]
A year has passed. If this isn't gonna end up on npm, please update the docs.

**Comment by vivek12345** [comment]
Thank you pointing out @jorisw . I have updated the README
